// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExampleMudSystem.Entities;

public partial class Category
{
    public int CategoryID { get; set; }

    public string CategoryName { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual ICollection<Lookup> Lookups { get; set; } = new List<Lookup>();
}