// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExampleMudSystem.Entities;

public partial class InvoiceLine
{
    public int InvoiceLineID { get; set; }

    public int InvoiceID { get; set; }

    public int PartID { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Part Part { get; set; }
}