// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExampleMudSystem.Entities;

public partial class Lookup
{
    public int LookupID { get; set; }

    public int CategoryID { get; set; }

    public string Name { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Customer> CustomerCountries { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> CustomerProvStates { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> CustomerStatuses { get; set; } = new List<Customer>();

    public virtual ICollection<Employee> EmployeeCountries { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeeProvStates { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeeRoles { get; set; } = new List<Employee>();

    public virtual ICollection<Part> Parts { get; set; } = new List<Part>();
}