// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExampleMudSystem.Entities;

public partial class UnitTest
{
    public int UnitTestID { get; set; }

    public string TableName { get; set; }

    public int ReferenceID { get; set; }
}