// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExampleMudSystem.Entities;

public partial class Employee
{
    public int EmployeeID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public int ProvStateID { get; set; }

    public int CountryID { get; set; }

    public string PostalCode { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int RoleID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual Lookup Country { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual Lookup ProvState { get; set; }

    public virtual Lookup Role { get; set; }
}